apiVersion: v1
kind: Pod
metadata:
  name: goapp
  namespace: demo
  labels: 
    app: godemo
spec:
  containers:
    - image: w22663/go-web-hello-world:v1
      name: goapp
      ports:
        - containerPort: 28082
          name: http
          protocol: TCP
  tolerations:
      - effect: NoSchedule
        key: app
        operator: Equal
        value: web
